[package]
name = "sipso-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph-generators = "0.1.0"
rand = "0.8.5" 
optlib-testfunc = "0.1.0"